### ISSUE TITLE
Error Reported By  |anshul.verma@sanskritii.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#31] opened 2018-06-03 04:59 UTC
Partner : OIR, User : anshul.verma@sanskritii.com 
Problem : Error : VariantCode  DRS-144 does not exist in Sku entity!! 

 Message : http://stompmarketapi.azurewebsites.net/Inventory/items/Sku%20Code/%20DRS-144?filters=status:Purchased&auth=dq-C_yZ0xY0_obYxbBsVO0PyqXSJ0jHlCjK_OoZi7r9_6YT6lszyItxlJoywp02vjrtZGCHGzu_kLn5R5e8KsiFk-__Hv60fcqEUGpDQfF-s8wavrsSsByzYCg9aCoXyeA5Qb_YK6MIxS7c0XOHR24_PTgS9WNX-qWo1RLPwFurd-Asp8QnEVPsuMCMi3tVW9R1EUUuWxTdceTXSq60jiHqnu_pw9mwFAZ68XVxE37OVQMwWpTD52iZhDsI3FHhlw8m5W04fKpVDSavO9MJHsS3k-7zIwoc5vsR1o28ALJy6pXZwDbXAp6fOuZMtQ7lg0lN6HB_c2D6f60CbKO4VJrOocT6tPwuqsokC1eyq7TpZe5aZpU9f7UAx8cFO0WKb_V7azjG0tR0DA10GlfFBgxSbuN-A2dkeW4x4OTf31LKJxVwLlFP65FQF2N4CsugkmryL99Os-g6lpGqJ4a72fuBRHdFnGnAHhhk6Cqsv5iUMpNCyLHFLIuHHcQE2ER51oR8bywHjMLdNC_nnQ6xr3q6HW3caQDkXcX35G3fPQ0tOks2FEDwCO6nCcVX-bYakbdpyc7Y4b3MZYFt7eFsSrhdRm6XPlkqEiTEfCbtGpArX8ph15Bb0ltfp-k_2P66NNJrFRTUl-joWqeXDbihDDTg8pW7YY1zwWDj99d1QlkhFmMsbuaduez7RgN_2LkQ31MtGPbSIuDH-YHGTiS918I2uY3Mn6kbsTwMREsmbjWplHu3QReacOjwc678f-K6ZZEBYHWRxdJ7GTPiYy2uLCWMr6IiTXnkEaogWbGV4-l1LvoViU5txmAxRr2m1m0Hz25_tH46PpKtxSrkJS4z0RixFeM-ABzFfzznpatX7e43T3ljKShZINZNZVpDdpf2GCvOJwpb2luWy89R9SMTiJISNcVvhvVvWNWeo3d7RIqcgRLykwlfovoAOlo-2itMBU4JCy9Wgdp37dnDGpH2CREuJfjoFjmZfq-4Ys_p5zWYfvLlSwi_S3MIdpMvDU__qAufiH4o-jln18oiECmA21DTG9bEGUxx_M3MdDOLp4ZboKXAxI9yiX5ninWG5q1jHsqMUsveyYkaXAGAMrV_20-E9EoJXxL-0Qtbtb9QXLTMBTyXj-SSlHacUpwI5By2MnrdbFCePhfgPS-s5__K4aDmsq7jBJQASnhJSUTEpKHL7g2tXqg3xNxvVR8MDls3C2VdTnhMha0lWgCLxpYa76X0Ds1wOEFrAoulJFgd5mAxmn0AJ8g8VaDItMJJpInW5qVm2_gyS6DAEVS6tlLjlx5W1PUvwIBePJEivTj2zBaOgzFRFGkW6Dk0K3frA-fgdSVpml3w5zXWojir-kcb9RSrLePETdxlThNqZnd-CV07ui2Nw_Je4A3LYvBukr8nYmqNmgboOD_H2JHdQ1Fv3phaIheBFZ1_99uYfi4Go4s_JSVG76ZVTdWNPVGw04u0wKemm015UhDXetTtwL2-a83g8YdFLcwspXFctDq9S2usrgisxgvvu36bYV_44NKJLvmZqtsusAXRxt1coiPVkYfSSYeedY1Tv2SfGgAmXUvgogYcEcERbtowfMcuFT9GA5lwjAjSJCO0O5hvAWx3PQNmGwV8-AcuNcpb-8o_J1hRdf-uwYOX93exK5eH0dkJ-gwW__D2qhEH1zIjG7brmdwehSNS3JHTA33uaMaDq9rmXKqf7CN5eNkvYbkOsS6HKjhpXziAoQJo6waBrD_lMwGDqq9R51tHKQ0PHDH-RaZ8WSXJZjpFkS1VYVK-jLGpO4uefnA5Pe5Y8aXpIhWLIiUzGNyCYkO3JmBnZCLQKR76jVtV_bv3uQZR-gy23FQOVDDlFIamUYX0cRlzAWwBR7OEsvdc 

 StatusText : Bad Request 

 User Comment : undefined 

Router Link : /inventory/finditems

**Comment by neetusingh1993** [comment] 2018-06-04 05:53
could not see the problem.Will see once you are here.

**Comment by neetusingh1993** [comment] 2018-06-09 05:06
This is not a bug.Closing this

**Closed by neetusingh1993** 2018-06-09 05:06 UTC
