### ISSUE TITLE
User Reported Problem - Verify actual sales |arushi2stompmarket@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#1015] opened 2019-02-25 06:06 UTC
Partner : OIR, User : arushi2stompmarket@gmail.com 
Problem : please verify actual sales of these SKUs.
Router Link : /catalog/brands/3

**Comment by anban4u** [comment] 2019-02-25 09:17
Aarushi, Can you please explain the problem better

**Comment by Arushi1Saxena** [comment] 2019-02-26 04:57
I was seeing sales with a great number for just 7 days. I also talked with Archana whether she has updated any DO. Later that evening Mahesh told me that it was due to Cloudtail. So, the problem is fixed. I just need to close this issue.

**Closed as completed** 2019-02-26 04:59 UTC
Labels: needs-discussion
