### ISSUE TITLE
User Reported Problem - I want details of those SKUs where qty is 0 |sumit.whitecherry@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#951] opened 2019-02-12 11:47 UTC
Partner : AESPL, User : sumit.whitecherry@gmail.com 
Problem : I want details of those SKUs where qty is 0
Router Link : /inventory/fulfillmentcenter/217

**Comment by anban4u** [comment] 2019-02-13 02:58
@vermaanshul didnt understand fully. Can you explain. Please reassign to nishant once done. He handles the dashboards and reports.

**Comment by vermaanshul** [comment] 2019-02-13 03:14
Team wants to know which SKUs have been created in stomp and which are not. The current inventory report gives the detail of only those SKUs where inventory is available however no data is available for the SKUs for which available inventory is zero....team needs SKU code for those variants also..

The problem is more specific when implementation is going on...I have provided data manually to the team..so this is not urgent however during implementation these kind of requirements will come.

**Closed as completed** 2019-07-24 10:55 UTC
Labels: enhancement, dashboards, needs-discussion
